#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
#  Post-deployment: parse broadcast JSON → generate deployments.json
#  This is the SINGLE SOURCE OF TRUTH for all contract addresses.
#  Frontend, tests, backend, scoring-service all read from this file.
# ═══════════════════════════════════════════════════════════════
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONTRACTS_DIR="$(dirname "$SCRIPT_DIR")"
PROJECT_ROOT="$(dirname "$CONTRACTS_DIR")"

CHAIN_ID="${1:-84532}"
BROADCAST="$CONTRACTS_DIR/broadcast/Deploy.s.sol/$CHAIN_ID/run-latest.json"

if [ ! -f "$BROADCAST" ]; then
    echo "❌ No broadcast found at: $BROADCAST"
    echo "   Run forge script first, then re-run this."
    exit 1
fi

echo "▸ Parsing broadcast: $BROADCAST"

# Parse the broadcast JSON to extract proxy addresses.
# Convention: each ERC1967Proxy CREATE follows its implementation CREATE.
# The factory pattern: impl CREATE → proxy CREATE (proxy wraps the impl).
# Non-proxied: direct CREATE with contractName.
OUTPUT=$(BROADCAST_FILE="$BROADCAST" python3 << 'PYEOF'
import json, os

broadcast_path = os.environ["BROADCAST_FILE"]
with open(broadcast_path) as f:
    data = json.load(f)

txs = data.get("transactions", [])

# Walk transactions in order. When we see an impl CREATE followed by
# an ERC1967Proxy CREATE, the proxy is the deployed address for that contract.
contracts = {}
last_impl_name = None
last_impl_addr = None

for tx in txs:
    cn = tx.get("contractName")
    addr = tx.get("contractAddress")
    tt = tx.get("transactionType")

    if tt != "CREATE" or not cn or not addr:
        continue

    if cn == "ERC1967Proxy":
        if last_impl_name:
            contracts[last_impl_name] = {
                "proxy": addr,
                "implementation": last_impl_addr,
                "proxied": True
            }
            last_impl_name = None
            last_impl_addr = None
    else:
        # If previous impl had no proxy, it's a direct deployment
        if last_impl_name:
            contracts[last_impl_name] = {
                "address": last_impl_addr,
                "proxied": False
            }
        last_impl_name = cn
        last_impl_addr = addr

# Flush last
if last_impl_name:
    contracts[last_impl_name] = {
        "address": last_impl_addr,
        "proxied": False
    }

# Build canonical output with consistent naming
canonical = {}
for name, info in contracts.items():
    key = name[0].lower() + name[1:]  # camelCase
    canonical[key] = info

print(json.dumps(canonical, indent=2))
PYEOF
)

echo "$OUTPUT"

# Get chain metadata
CHAIN_NAME="unknown"
RPC_URL="unknown"
case "$CHAIN_ID" in
    84532) CHAIN_NAME="base-sepolia"; RPC_URL="https://sepolia.base.org" ;;
    8453)  CHAIN_NAME="base-mainnet"; RPC_URL="https://mainnet.base.org" ;;
esac

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Write the canonical deployments.json at project root
DEPLOY_JSON="$PROJECT_ROOT/deployments.json"
python3 << PYEOF
import json

contracts = json.loads('''$OUTPUT''')
manifest = {
    "chainId": $CHAIN_ID,
    "chainName": "$CHAIN_NAME",
    "rpcUrl": "$RPC_URL",
    "deployedAt": "$TIMESTAMP",
    "contracts": contracts,
    "wallets": {
        "deployer": "$(grep DEPLOYER_ADDRESS "$CONTRACTS_DIR/.env" 2>/dev/null | cut -d= -f2 || echo 'unknown')",
        "admin": "$(grep ADMIN_ADDRESS "$CONTRACTS_DIR/.env" 2>/dev/null | cut -d= -f2 || echo 'unknown')",
        "operator": "$(grep OPERATOR_ADDRESS "$CONTRACTS_DIR/.env" 2>/dev/null | cut -d= -f2 || echo 'unknown')",
        "scorer": "$(grep SCORER_ADDRESS "$CONTRACTS_DIR/.env" 2>/dev/null | cut -d= -f2 || echo 'unknown')",
        "guardian": "$(grep GUARDIAN_ADDRESS "$CONTRACTS_DIR/.env" 2>/dev/null | cut -d= -f2 || echo 'unknown')"
    }
}
with open("$DEPLOY_JSON", "w") as f:
    json.dump(manifest, f, indent=2)
print(f"✅ Written: $DEPLOY_JSON")
PYEOF

# Also generate TypeScript constants for the frontend
FRONTEND_CONTRACTS="$PROJECT_ROOT/frontend/src/lib/contracts.generated.ts"
python3 << PYEOF
import json

with open("$DEPLOY_JSON") as f:
    manifest = json.load(f)

lines = [
    '// AUTO-GENERATED by contracts/script/post-deploy.sh',
    '// DO NOT EDIT MANUALLY — re-run post-deploy.sh after any deployment',
    f'// Generated: {manifest["deployedAt"]}',
    '',
    'import { type Address } from "viem";',
    '',
    f'export const CHAIN_ID = {manifest["chainId"]};',
    f'export const CHAIN_NAME = "{manifest["chainName"]}";',
    f'export const RPC_URL = "{manifest["rpcUrl"]}";',
    f'export const DEPLOYED_AT = "{manifest["deployedAt"]}";',
    '',
    'export const CONTRACTS = {',
]

for name, info in manifest["contracts"].items():
    addr = info.get("proxy", info.get("address", ""))
    lines.append(f'  {name}: "{addr}" as Address,')

lines.append('} as const;')
lines.append('')
lines.append('export const WALLETS = {')
for role, addr in manifest["wallets"].items():
    lines.append(f'  {role}: "{addr}" as Address,')
lines.append('} as const;')
lines.append('')

with open("$FRONTEND_CONTRACTS", "w") as f:
    f.write('\n'.join(lines))
print(f"✅ Written: $FRONTEND_CONTRACTS")
PYEOF

echo ""
echo "═══════════════════════════════════════════════════"
echo "  Deploy manifest generated successfully"
echo "  Source of truth: $DEPLOY_JSON"
echo "  Frontend types:  $FRONTEND_CONTRACTS"
echo "═══════════════════════════════════════════════════"
