// AUTO-GENERATED by contracts/script/post-deploy.sh
// DO NOT EDIT MANUALLY — re-run post-deploy.sh after any deployment
// Generated: 2026-03-14T09:11:33Z

import { type Address } from "viem";

export const CHAIN_ID = 84532;
export const CHAIN_NAME = "base-sepolia";
export const RPC_URL = "https://sepolia.base.org";
export const DEPLOYED_AT = "2026-03-14T09:11:33Z";

export const CONTRACTS = {
  eloSystem: "0xce199214adaa02347a12316c0d63c35ab03dbb40" as Address,
  bountyRound: "0x3b46604a99d65737ccc7486e54c85da1daedff09" as Address,
  treasury: "0xa464f7c3161f5e21f3ba3c1e8eaab322187c7512" as Address,
  scoringOracle: "0xf40f73f2e187c33d1afb16284bfb1fb1fa3148aa" as Address,
  arenaRegistry: "0x4beb403789b1cc5eef1c29718a593fb9a7f19864" as Address,
  stableRegistry: "0xc35c7b1d96f55a269e55649e7fb57aaf02c69757" as Address,
  bountyFactory: "0xd83547cce3f11684c8a3dc12f7f4f28c67324e3a" as Address,
  seasonManager: "0xca0f3044fb4c18a590941326f6252d9e23d9e554" as Address,
  bountyMarketplace: "0x90fa3f817079014ae82a14139d7448fa229f1653" as Address,
  arbitrationDAO: "0xf9a937bf915063fdf481d08a57d276d380c7caeb" as Address,
  timelockGovernor: "0x439b7b7a00edc420753c0a56e0b7dbf3419b7f00" as Address,
  emergencyGuardian: "0x39a2ad5c4be3bd4faac905aa1ff917050d6966e3" as Address,
} as const;

export const WALLETS = {
  deployer: "0x4357862Ee5e8EDCD2918742cAc9b1e2D4454B473" as Address,
  admin: "0x10D7dCfe54751e229B10BDfDF62cA91ae5f22B5f" as Address,
  operator: "0x8c35c1930CAd1224e7A1F90E9f7df5486e7489d2" as Address,
  scorer: "0x758719d3f12ba9779AFBBCB83b6f9E594DBEf381" as Address,
  guardian: "0x677394E4593Cc833e000BBB81Eb9031aD2aE0c4B" as Address,
} as const;
