// AUTO-GENERATED by contracts/script/post-deploy.sh
// DO NOT EDIT MANUALLY — re-run post-deploy.sh after any deployment
// Generated: 2026-03-19T14:46:40Z

import { type Address } from "viem";

export const CHAIN_ID = 84532;
export const CHAIN_NAME = "base-sepolia";
export const RPC_URL = "https://sepolia.base.org";
export const DEPLOYED_AT = "2026-03-19T14:46:40Z";

export const CONTRACTS = {
  eloSystem: "0x92fcf0e3cc587d6656de79725ae01badb3026d21" as Address,
  bountyRound: "0x552b47f8ec1cad24c33e657019811be444e8701a" as Address,
  treasury: "0xd5503c65d01e8d22a8bac4eed347dd5ad744cbd5" as Address,
  scoringOracle: "0xb7597d71e00cd1c45c51dd093ce0d3dbd5b86e91" as Address,
  arenaRegistry: "0xc8096d0db341e3a4b372bccfe95b840bc680c2d5" as Address,
  stableRegistry: "0x5894cc167d53ce33fec45c6e9bdcd80e9c4c1618" as Address,
  bountyFactory: "0x99c1500edfd3cbd70b6be258db033c7a8dd5a8b8" as Address,
  seasonManager: "0x446a0b6f91ebe62615664c19eee2983e36244268" as Address,
  bountyMarketplace: "0x343635bc16b819d145f2f7e254164e2545af9dc3" as Address,
  arbitrationDAO: "0xb4b0add468f024bf6268b2c9f913cc9f83586fba" as Address,
  timelockGovernor: "0x26ec86440f4a2075289135f992bf6a4e1e7033cb" as Address,
  emergencyGuardian: "0x6b7127e727aa4ebf0d6502b94f97af90b3eec1b1" as Address,
} as const;

export const WALLETS = {
  deployer: "0x4357862Ee5e8EDCD2918742cAc9b1e2D4454B473" as Address,
  admin: "0x10D7dCfe54751e229B10BDfDF62cA91ae5f22B5f" as Address,
  operator: "0x8c35c1930CAd1224e7A1F90E9f7df5486e7489d2" as Address,
  scorer: "0x758719d3f12ba9779AFBBCB83b6f9E594DBEf381" as Address,
  guardian: "0x677394E4593Cc833e000BBB81Eb9031aD2aE0c4B" as Address,
} as const;
