// AUTO-GENERATED by contracts/script/post-deploy.sh
// DO NOT EDIT MANUALLY — re-run post-deploy.sh after any deployment
// Generated: 2026-03-19T11:59:47Z

import { type Address } from "viem";

export const CHAIN_ID = 84532;
export const CHAIN_NAME = "base-sepolia";
export const RPC_URL = "https://sepolia.base.org";
export const DEPLOYED_AT = "2026-03-19T11:59:47Z";

export const CONTRACTS = {
  eloSystem: "0x6fdbf63d40daf4a48c45bfc5720206125da417cb" as Address,
  bountyRound: "0xe9c542cfc7251a3aec31096477f0f75f1e4e9f57" as Address,
  treasury: "0x7dffa752f0336327a880b3a0024117beaeda9182" as Address,
  scoringOracle: "0x0eea4ed07c153c9f1eb74e53471855875e1e88db" as Address,
  arenaRegistry: "0x2e3f7a611516a9e181c377141dbbed7e8a34f1ec" as Address,
  stableRegistry: "0x42bb09cf2182ac1f6b22787ef617b83aa7b4b94c" as Address,
  bountyFactory: "0x81a4c7cf6fce39108d674470d3fdfd19b739dd92" as Address,
  seasonManager: "0x3419a3a2d410266c88f043068baa6c564cbf37d0" as Address,
  bountyMarketplace: "0x2a6af2e255adb5139b3416835fa0dbef78cd0508" as Address,
  arbitrationDAO: "0xd55e30ecbf63ad5d75044a630bb55a37ca264e1a" as Address,
  timelockGovernor: "0x62cd74606cf39bd89127b397f2a183f936d0ba26" as Address,
  emergencyGuardian: "0x69464cd83c7473a7de93a84465ba0876de48096b" as Address,
} as const;

export const WALLETS = {
  deployer: "0x4357862Ee5e8EDCD2918742cAc9b1e2D4454B473" as Address,
  admin: "0x10D7dCfe54751e229B10BDfDF62cA91ae5f22B5f" as Address,
  operator: "0x8c35c1930CAd1224e7A1F90E9f7df5486e7489d2" as Address,
  scorer: "0x758719d3f12ba9779AFBBCB83b6f9E594DBEf381" as Address,
  guardian: "0x677394E4593Cc833e000BBB81Eb9031aD2aE0c4B" as Address,
} as const;
